### ISSUE TITLE
Emoticon的panel的删除图标不是最后一个图标。

### ISSUE THREAD

**Issue by hifall** [sagesse-cn/swift-chat#13]
Emoticon的panel的删除图标不是最后一个图标。

复制办法：
1 把iPad竖直放置，打开app；
2 打开emoticon的panel，这时候删除图标位于最后一个位置；
3 把iPad切换到水平方向；
4 这时候删除图标不位于最后一个位置。

**Comment by SAGESSE-CN** [comment]
目前还没有完全支持横屏，不过应该很快就支持了

**Comment by hifall** [comment]
好的。

**Comment by hifall** [comment]
请问支持横屏了吗？好期待。
