### ISSUE TITLE
iOS 10 长文字消息被截断

### ISSUE THREAD

**Issue by hifall** [sagesse-cn/swift-chat#20]
在以下的情况下，消息气泡不能完整显示整条文字消息：
1 在界面中输入一条消息，然后按Home键，把app带到background；
2 点app，然后粘贴一条长文字消息（>300字符），该消息出现在界面中，但是后面的部分会被截掉。

**Comment by hifall** [comment]
看起来好像是AutoLayout约束不能被满足。出错信息：

2016-10-03 12:46:32.048885 SIMChatExample[83341:12919072] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60800028f550 UITableViewCellContentView:0x7fc3f0e3bc00.width == 320   (active)>",
    "<NSLayoutConstraint:0x60000028a5f0 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fc3f0e3bc00.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60800028f550 UITableViewCellContentView:0x7fc3f0e3bc00.width == 320   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
[INFO] SIMChatBaseMessageCell.retryLoadImage(_:url:defaultImage:displayLoadingIndicator:completionHandler:): Downloading https://www.mychat.com/uploaded/tenant_1/images/agent_2_photo.png?57eccc04ad41c completed.
2016-10-03 12:46:34.671421 SIMChatExample[83341:12919072] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x608000289ba0 UITableViewCellContentView:0x7fc3f0e438c0.width == 320   (active)>",
    "<NSLayoutConstraint:0x6080002929d0 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fc3f0e438c0.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x608000289ba0 UITableViewCellContentView:0x7fc3f0e438c0.width == 320   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
[DEBUG] SIMChatViewController+Message._appendMessages(_:animated:): self: false lasted: true
[INFO] SIMChatBaseMessageCell.retryLoadImage(_:url:defaultImage:displayLoadingIndicator:completionHandler:): Downloading https://www.mychat.com/uploaded/tenant_1/images/agent_2_photo.png?57eccc04ad41c completed.

**Comment by hifall** [comment]
我试了一下，好像设置 table view 的 estimatedRowHeight 可以解决这个问题，但是同时导致另外一个问题：当添加新消息的时候，UI会上下翻滚。

**Comment by hifall** [comment]
貌似 SIMChatBaseMessageCell 中初始化时添加的约束会使得 bubbleView.contentView.hasAmbiguousLayout() 为 true，即 contentView 的 layout 不唯一，不知道跟这个问题有没有关系。

**Comment by SAGESSE-CN** [comment]
没有重现这个问题
https://github.com/sagesse-cn/swift-chat/tree/custom

**Comment by hifall** [comment]
你上面链接中的 custom repo 也可以重现呀，具体：

1 在 Xcode 中启动 app；
2 按 Home 键来把它退到 background，再点击 app 的 icon 来把它带到 foreground；
3 重复第2步中的步骤2次；
4 在 app 中发送一条文本消息；
5 Xcode 的控制台中会显示：
SIMChatExample[75303:1379583] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600000097070 UITableViewCellContentView:0x7fd9d3f956b0.width == 320   (active)>",
    "<NSLayoutConstraint:0x600000483e80 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fd9d3f956b0.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600000097070 UITableViewCellContentView:0x7fd9d3f956b0.width == 320   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by hifall** [comment]
我按照出错消息中的建议，添加一个 UIViewAlertForUnsatisfiableConstraints 符号断点，也可以捕获这个异常。

**Comment by hifall** [comment]
这是捕获的异常截图：

<img width="1209" alt="screen shot 2016-10-08 at 5 39 32 pm" src="https://cloud.githubusercontent.com/assets/5734293/19212155/5835e8d6-8d7e-11e6-8f9d-4a6dbeabd113.png">

**Comment by hifall** [comment]
当试图添加 widthFenceConstraint 的时候，就有可能会出现；如果出现的话，长文本信息就被截断了。

这个 bug 可重现的几率大概是70%。

**Comment by hifall** [comment]
当试图重现失败时，请重复几次：按 Home 键来把 app 退到 background，再点击 app 的 icon 来把它带到 foreground，然后会出现的。

**Comment by SAGESSE-CN** [comment]
custom那个分支有没有这个问题？

**Comment by hifall** [comment]
有的，已经确认了。
