### ISSUE TITLE
为什么运行起来进入不了聊天界面？

### ISSUE THREAD

**Issue by hifall** [sagesse-cn/swift-chat#3]
停留在这个画面上进不去了。请看截图。谢谢！
<img width="375" alt="screen shot 2016-06-27 at 11 55 27 am" src="https://cloud.githubusercontent.com/assets/5734293/16368213/2f8e296e-3c5e-11e6-80b8-6b9fb66d6258.png">

**Comment by SAGESSE-CN** [comment]
😳改下入口，在main.storyboard里

**Comment by hifall** [comment]
怎么改呢？能具体些吗？

**Comment by hifall** [comment]
如果能把项目改成编译后就能看到聊天界面，就更好了。

**Comment by SAGESSE-CN** [comment]
好的，😄其实是我忘了切换回来就提交了

**Comment by SAGESSE-CN** [comment]
己经改过来了
